---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-installer
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
      - subscriptions
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: everest-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: everest-installer
subjects:
  - kind: ServiceAccount
    name: everest-installer
    namespace: {{ .Release.Namespace }}
