{{- if .Values.server.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: everest-jwt
  namespace: {{ .Release.Namespace }}
data:
  id_rsa: {{ genPrivateKey "rsa" | b64enc  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: everest-accounts
  namespace: {{ .Release.Namespace }}
  annotations:
    insecure-password/admin: "true"
data:
  users.yaml: {{ tpl (.Files.Get "everest-admin.yaml") . | b64enc }}
{{- end }}
