---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-uninstaller
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
    verbs:
      - delete
      - list
  - apiGroups:
      - everest.percona.com
    resources:
      - databaseclusters
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: everest-uninstaller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: everest-uninstaller
subjects:
  - kind: ServiceAccount
    name: everest-uninstaller
    namespace: {{ .Release.Namespace }}
