apiVersion: v1
kind: ServiceAccount
metadata:
  name: everest-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: everest-admin-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: everest-admin-cluster-role
rules:
  - apiGroups: ["everest.percona.com"]
    resources: ["databaseengines"]
    verbs: ["get", "list", "update"]
  - apiGroups: ["everest.percona.com"]
    resources: ["databaseclusters", "databaseclusterbackups", "databaseclusterrestores", "backupstorages", "monitoringconfigs"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "namespaces"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes", "pods", "persistentvolumes"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["list"]
  - apiGroups: ["everest.percona.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "issuers", "clusterissuers"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: everest-admin-cluster-role-binding
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: everest-admin-cluster-role
subjects:
  - kind: "ServiceAccount"
    name: everest-admin
    namespace: everest-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: everest-admin-role-binding
roleRef:
  kind: "Role"
  apiGroup: "rbac.authorization.k8s.io"
  name: everest-admin-role
subjects:
  - kind: "ServiceAccount"
    name: everest-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: everest-jwt
data:
  id_rsa: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWFFJQkFBS0JnUUM5ZUwzVS9VbnR3SFhDMlBHbkRLNDVlODRtcXUxL2dwclYwS3FpSGEwTDNpd2RmYVViCm5TWkhlTUNtaE9hVWM0ODNWVmlJeTN6NlovdWRjZktNblgrUjgwK2FUWlZ4MVBLdnNFZzQ2TUd5MHpaaU16dy8KL285UVdUNU9POU1iVkp5VjdHOG9rNmdTWW1SY0w2RUQxOEtubjRtRlNuYkZYZDZHa0dZY2tldHo2d0lEQVFBQgpBb0dBZUt4SjJ6bG11SEgzanAyMWF2dDhpMGY2eUUzYzdYVTFRRENpUEpaQi9Ha0lGOUJLTkFnbXRTYUhMSWRBCmhCUUZodXhvY3RlSFJjU3NVRjZlYUVoM1VsaFgvMk1WYmY2WEFWSFdseC9kNVgrRE9hdjNxZmlDa09pUDB0WkwKWkJXRXlLY0hPQnJWRkpCNGxTUmc0TkV0OXpYUFEvSWlRQllqQXlZb1VpUnFDUUVDUVFET3l0M3AvK3Rzemx6UgorYm0xT3diaHNzc1lTNVJiS0w4Mi81MS8vVzR5VkdrQ2NqdkQ2SDRldUhPSjVENEp4T3NNZWdKV3JUVHpZWXRVCjNaaVhGWHBMQWtFQTZvNi9OMFhWOTNUZGttREszclczbk1YeHZBT3lMLzYxOW4rVlY1UjBGdXI4aVZSWFB6R1cKUGZMR01vc2NaSlRDSHNqTUUzaGxXOFlucDRGbU1VWG80UUpBWHJPZkR6T3BZQ25kYmplOEtWZi8zY3Fnb2Q2eQo4VkJteVV3a2wrRzYzb2V6azNBM0dJL1hla0FrZ1dpcVZKVCt3N2I0YlROalJYWk5kYThKMjE3MW93SkJBSlhwCi9INzRUS1FuZG9KYkNPN0ZHQURFWnhkekNVMHhyOTFIZUEwTTNoSFR5T3FCRkc1WVpCMWQ4SjFYV2lOVERLc2UKVFlqWU4zZ3JzeWFWUnRxUlF5RUNRUUNXdWdvUHdrT3B6QjVxMmdoR3F4Z1RiRjRBczRQd0VwNFF3YXYwTUwwMQpleVlFanN5ZVlkUzhPUW82Z0RyaFFqVDF0dlllcFJPNVNHYlUyalB2c0hmdwotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  id_rsa.pub: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JR0pBb0dCQUwxNHZkVDlTZTNBZGNMWThhY01yamw3emlhcTdYK0NtdFhRcXFJZHJRdmVMQjE5cFJ1ZEprZDQKd0thRTVwUnpqemRWV0lqTGZQcG4rNTF4OG95ZGY1SHpUNXBObFhIVThxK3dTRGpvd2JMVE5tSXpQRC8rajFCWgpQazQ3MHh0VW5KWHNieWlUcUJKaVpGd3ZvUVBYd3FlZmlZVktkc1ZkM29hUVpoeVI2M1ByQWdNQkFBRT0KLS0tLS1FTkQgUlNBIFBVQkxJQyBLRVktLS0tLQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: everest-accounts
  annotations:
    insecure-password/admin: "true"
data:
  # username: admin | password: admin
  users.yaml: YWRtaW46CiAgcGFzc3dvcmRIYXNoOiBhZG1pbgogIGVuYWJsZWQ6IHRydWUKICBjYXBhYmlsaXRpZXM6CiAgICAtIGxvZ2lu
---
apiVersion: v1
kind: Secret
metadata:
  name: everest-tls
data:
  # self-signed certificates, used for testing only (valid for 100 years).
  # To use these certificates, uncomment the below lines, and in everest-settings configmap,
  # set insecure="false"
  #
  # tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZakNDQWtxZ0F3SUJBZ0lRTjUzTUdyZDRyck15THJYWnl6OUZDVEFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFLRXdkQlkyMWxJRU52TUI0WERUSTBNREV3TVRBd01EQXdNRm9YRFRNek1USXlPVEF3TURBdwpNRm93RWpFUU1BNEdBMVVFQ2hNSFFXTnRaU0JEYnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUx4QkgwMVlad05tWG1TOUdyNzZqUDlTRUcrTXppV3B6aWo3M01yMVlIRkJpTFdkQW12YVdrangKQkFwUzJrTUUySXFvbFB6MGo4YmRKYmx1WXVweWhOYXNPOVVFam5HS0xLVlpnb3JmczFhT2lTMUFmdm9JWk9zRQprQnlxb3EzdFNSQ21FTHQ3OW9sWWlwTGoyTStlWFcvLzU3d0lIaUovQW42cVJEWDBjdjdmMElLSi9oVklOVVlZCmNKOFZvYm1IeE95OGJ4dGtsSmlpeUJscUxCbzU3cTFjck0velJ6bnRHRStVdWwvTmlBS1pNd2lhMEZXM29LK20KamhtZTFIa3ZTQzMxbGVlQXRSQSsxaGp5SHVodWFTQlU4UTVQdFJJc2gzd3Vzb3MzYUx6V2pTOFJGQTJYTmlVSQp1RGN2ZzZVeEErZUF6VHZ3UjNKNGZjdjBCYWNETW1NQ0F3RUFBYU9Cc3pDQnNEQU9CZ05WSFE4QkFmOEVCQU1DCkJhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQjdCZ05WSFJFRWREQnkKZ2dsc2IyTmhiR2h2YzNTQ0IyVjJaWEpsYzNTQ0ZtVjJaWEpsYzNRdVpYWmxjbVZ6ZEMxemVYTjBaVzJDR21WMgpaWEpsYzNRdVpYWmxjbVZ6ZEMxemVYTjBaVzB1YzNaamdpaGxkbVZ5WlhOMExtVjJaWEpsYzNRdGMzbHpkR1Z0CkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3JYNzBXQVBtRnI1ZGoKQkhndFcwcURTWEpRNXpSa0pwNXpqUlVIYzZSbVhIQXJlYVVHMHpQVDkyamlXeG5FdWVzQjZUYUF1dEtxSVlhQwp4bXFwZzFLL0loZWdBTnQxTDVzM0xsQXlsbFUrNkwrMEs1RzY3dkNEZGpjOTJtWEJ5U2E3dzdUMFFBeTVubnRDCm5URlEyQk1JVzMzQkR6SGdDL0Z3ZWJKWVNaSTArQk40TmhUS1g3aFdWbWtiMWhacnN3Y29pWGZKUUFuL3QrUTMKbVdwd0I2aWVqdUdXTlBsdkkvV2h1K2Q4VHE2aGl3WjRyRmtZUEhUNVRPdHh1Sk0zdlRYRzJoSllPYWdvc0IrVgpUTkVxQ0trb2VMSTBNbnFvbjhCQzNLV0tLVHM0aitFY2ZhMTQyWmVyR05xSWNNTDdkUnB2bTh3WVpXV1FXbmJyCm9VbEtrOFRKCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  # tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzhRUjlOV0djRFpsNWsKdlJxKytvei9VaEJ2ak00bHFjNG8rOXpLOVdCeFFZaTFuUUpyMmxwSThRUUtVdHBEQk5pS3FKVDg5SS9HM1NXNQpibUxxY29UV3JEdlZCSTV4aWl5bFdZS0szN05Xam9rdFFINzZDR1RyQkpBY3FxS3Q3VWtRcGhDN2UvYUpXSXFTCjQ5alBubDF2LytlOENCNGlmd0orcWtRMTlITCszOUNDaWY0VlNEVkdHSENmRmFHNWg4VHN2RzhiWkpTWW9zZ1oKYWl3YU9lNnRYS3pQODBjNTdSaFBsTHBmellnQ21UTUltdEJWdDZDdnBvNFpudFI1TDBndDlaWG5nTFVRUHRZWQo4aDdvYm1rZ1ZQRU9UN1VTTElkOExyS0xOMmk4MW8wdkVSUU5sellsQ0xnM0w0T2xNUVBuZ00wNzhFZHllSDNMCjlBV25BekpqQWdNQkFBRUNnZ0VBWnhMVSs3bGFkYzhZQWRwVWlacVBsc0F0QlphM3pJRmp3cWJjWmpmaHZVRWYKaENqYWlZajloQkNLb01ocWZ1VnBWc29sQVRjNmZhemFHZVJwdm1wRGQzTElNOE1SNXZLN3JURU1POU50MHdlcAo3aC94Smg5d2VnbCtpbU9YUE5tOTlxS21hTERmOUtXSkFoSkV4TEMyQWp2QWV3Q0sxMkpwVUVjVG4rTWZENU0wClR5dEtFTnRvSXlIZHhSWDdBODUwclo3ZW5XY3ZXdElqRDBYa3piTTFQTGZsZHcraUJsT3pqYzVmWUxpRjlZc1AKTGJsQnFZR00vUjJYWWp0dHlVNTNDODM0ZDMxL2dYU1ZuMUk2VFpKdFRhU09pNFk1S0llTlRlVDJLRlptWTZJUwptbVZzdzhKcmNIYm5BemJicXcyeC9xTTBMdmdFL2QrR0RjZTlWZGMwS1FLQmdRREZpbDdGd05uVVk3M3BlYm1GCjV3MTI5ZlhjNjlxRVk5TjNWQkJFNGU2dm8wWWtiZ2NaUWw4SVFkUFcvYnd6ZDBLbXlTVXg3MW1tWTVLZENXMGoKUHRiNFRRYlAya0J6Y3NNSEVuVWNsU3Zzc051YllTMVJ6dmloRWlOZ3BYVFBBZ2RWV1pnL1pSbUh6aTRjQzRVKwozMFVNMWVpdTQyTm9yck1kcjBmc1I2ZnI5UUtCZ1FEejl6eXlpRHJjbW5SREUvUXlhUys1N1Q5YVgwVHBpNlVkCjgwdmdhcXRMdGQreWZVdlNRMVpmakM1T1BXdGxXaXNhR2NYaVRIWUFwRmJibVBCRGRpU1NVMWhtOE85cTZLZzIKUmdqWjQ3UGZVczFlUS9LcFc5YnJnVU96cjJnMzBZSHFrcjZsVWg4dmtoMjU0bE5SRU8rd1dlZnlDbW43MW5kZwpiazNySGQvRjl3S0JnUUNLODJqMHExSE9MeGJBS3lwUHdSWGNqdWlScktsNXBJcDBEb0tmSVZsMjNGK1RjbjIxCnk5VHpCdkxPOEk0NG1YUWR3N0ZSTGE2ZTlyMkRqc1RoSE91em51TGl3LysvOVlLdjc5REcrVHI3Yy9BVm5NWjMKSENJUmtxT2w4Tng0WEZIeVBHSjJmVlAzRGhXckRvTjhsU3FKKzlGL2ExMWFua0JKNmlpcVVFRVRIUUtCZ1FDVQpIdkhkTzFUeGgxMDdOS3c0eHlCUTlEaFl1Q3J3MlBZaEh3eGNicWNkeW9qTXA4SVhJUWNaNzlSVmNIajZDaXJOCktBUzdCczFHU29EcHh3dHBDaHZlTTNnaTEvbWtvU2t2K29sNU1RU09mSWx2eURWV21nbjg1bmlpYWNjT3pNYmkKRXNKcFFWanAydjd0VXZwZTU3ZC9ETGNFZjBvbHV1cXp3NFRQVVU0QnRRS0JnQ1A1TG5yMlVpbjV0V0dtK0NZawp2QnptMzk2bWl2U1RxZWdxamk1TUZrUmUrMWR2K0RIemo0dENvWmFRZkxwblhTalhyZnNlelhnTTYzYVl1RkN4CnZvbndRbGgzT3BQelFPOHE0blNscWFaTEVwRDQxMlRTVktMTUVWaDg5cWtpdVFMaGNtbHozaU53emphK3B5NkcKTWx4Ulc2OWhURGx4UzlFSW4xRGpEclVmCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0= 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: everest-settings
data:
  insecure: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: percona-everest
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: everest
      app.kubernetes.io/component: everest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: everest
        app.kubernetes.io/component: everest
    spec:
      serviceAccountName: everest-admin
      automountServiceAccountToken: true
      volumes:
      - name: jwt-secret
        secret:
          secretName: everest-jwt
      - name: tls-secret
        secret:
          secretName: everest-tls
      containers:
        - name: everest
          image: perconalab/everest:0.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 15
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
          - name: jwt-secret
            mountPath: /etc/jwt
          - name: tls-secret
            mountPath: /etc/ssl/certs
---
apiVersion: v1
kind: Service
metadata:
  name: everest
  labels:
    app.kubernetes.io/name: everest
    app.kubernetes.io/component: everest
spec:
  selector:
    app.kubernetes.io/component: everest
    app.kubernetes.io/name: everest
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
---
